manifest = "09c527fc506b4e084fe22e92dc17f59674eda4ad68bb69418ba6a050c8ef7fca"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[[dependency]]
package = "github.com/buckaroo-pm/nodejs-http-parser"
target = "//:http-parser"

[[dependency]]
package = "github.com/buckaroo-pm/openssl"
target = "//:openssl"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "1.2.11" ]
revision = "94a70f3274f15bf98b472178e91fd57a6e6c53d8"

[lock."github.com/buckaroo-pm/nodejs-http-parser"]
versions = [ "branch=master" ]
revision = "a8c9a87b3a284fe7a82f9ee93c6bb29eecbc6a86"

[lock."github.com/buckaroo-pm/openssl"]
versions = [ "tag=1.0.2p" ]
revision = "1f1935327083eabb14370b43049f37839975c36f"
