targets = [ "//:git2" ]

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
version = "*"

[[dependency]]
package = "github.com/buckaroo-pm/nodejs-http-parser"
version = "*"

[[dependency]]
package = "github.com/buckaroo-pm/openssl"
version = "tag=1.0.2p"
